//----------------------------------------------------------------------------//

#define White                   0xFFFFFFAA
#define Azul                    0x0000FFAA
#define Green                   0x00FF40AA
#define Verde_Escuro            0x00C40AAA
#define Red                     0xFF0000AA
#define Yellow                  0xFFFF00AA
#define Orange                  0xFF8000AA
#define Rosa                    0xFF00FFAA
#define Roxo                    0x8000FFAA
#define Grey                    0x808080AA
#define Erro                    0xFF4000AA
#define adm                     0x76EE00AA
#define C_PROPERTY              0xFFD700AA
#define C_VIP                   0x00E100AA

//----------------------------------------------------------------------------//

//Login 1 - 17
#define main_reais_vip          18
#define bank                    19
#define bank_balance            20
#define bank_draft              21
#define bank_deposit            22
#define bank_transfer           23
#define bank_transfer_value     24
#define main_cnh                25
#define main_fines              26
#define government              27
#define tuning                  28
#define paintjob                29
#define police                  30
#define neon                    31
#define arena                   32
#define arena_kits              33
#define rename                  34
#define colorname               35
#define wheel                   36
#define radio                   37
#define vip_color_tag           38
#define agency                  39
#define armedforces             40
#define hospital                41
#define hospital_sex            42
#define events                  43
#define vipss                   44
#define vip_area                45
#define mob                     46
#define honest                  47
#define transport               48
#define nitro                   49
#define hydraulic               50
#define main_reais              51
#define tanker_fuel             52
#define townhall                53
#define townhall_star           54
#define townhall_iptu_house     55
#define townhall_iptu_business  56
#define buy_cannabis            57
#define buy_weaponpiece         58
#define cost_accessories        59
#define cost_accessories1       60
#define school_bag              61
#define school_bag_weapon       62
#define school_bag_get          63
#define school_bag_acce         64
#define school_bag_acce_edit    65
#define school_bag_acce_sell    66
#define anticheat               67
#define realestate              68
#define base_menu               69
#define base_name               70
#define base_vehicle            71
#define base_vehicle_state      72
#define base_weapon             73
#define base_members            74
#define base_members_alter      75
#define base_members_add        76
#define base_members_add_sub    77
#define base_dm                 78
#define base_tag                79
#define base_lock               80
#define base_locked             81
#define base_pass               82
#define base_code               83
#define study                   84
#define help                    85
#define main_concessionaire     86
#define weapon_producer         87
#define wp_get                  88
#define hud                     89
#define hudbackcolor            90
#define hudcolor                91
#define hudfontcolor            92

//Banimento     96 - 99
//Imobilária    100 - 200
//Houses        5000 - 5015
//Companys      5016 - 5050
//Vehicles      5051 - 5059
//GPS           5060 - 5073
//#define MAIN_FUEL 5100

//----------------------------------------------------------------------------//

#define MAX_GAS_MAP         32
#define MAX_GAS_VEHICLE     6

//----------------------------------------------------------------------------//

//#define MAX_ACCESSORIES_CONNECT   5 //0-4 acessories
#define ATTACH_INDEX_PROFISSION     5
#define GS_PISTOL                   6
#define GS_SHOTGUN                  7
#define GS_SUBMACHINEGUN            8
#define GS_MACHINEGUN               9

//----------------------------------------------------------------------------//

#define MAX_MAIN_VEHICLES           10
#define MAIN_VEHICLES               5051
#define MAIN_VEHICLES_EDIT          5052
#define MAIN_VEHICLES_EDIT_MSG      5053
#define MAIN_VEHICLES_EDIT_PLATE    5054
#define MAIN_DEALERSHIP             5055
#define MAIN_VEHICLES_EDIT_COLORS1  5056
#define MAIN_VEHICLES_EDIT_COLORS2  5057
#define MAIN_VEHICLES_RELEASE_INPUT 5058
//5059 SHOPPING CONCESSIONAIRE

//----------------------------------------------------------------------------//

#define MAX_BASES               (3)
#define MAX_BASE_SUB            (1)
#define MAX_BASE_MEMBERS        (20)
#define MAX_BASE_NAME           (30)
#define MAX_BASE_TAG_NAME       (10)
#define MAX_VEHICLE_BASE        (4)
#define MAX_BASE_PASS           (10)
#define BASE_VEHICLE_MODEL      (560)
#define BASE_MONEY              (250000)
#define BASE_REAIS              (25)
#define BASE_PICKUP_SELL        (1313)
#define BASE_PICKUP_BUY         (1313)
#define BASE_MAP_SELL           (62)
#define BASE_MAP_BUY            (59)

#define color_base 0x00FFFFAA

//----------------------------------------------------------------------------//

#define MAX_HOUSES (874+1)

#define MAIN_HOUSE_COMMAND              2001
#define MAIN_HOUSE                      2002
#define MAIN_HOUSE_ALTER_MSG            2003
#define MAIN_HOUSE_ALTER_PASS           2004
#define MAIN_HOUSE_RELEASE_AGREE        2005
#define MAIN_HOUSE_PASS                 2006
#define MAIN_HOUSE_SELL_INPUT           2007
#define MAIN_HOUSE_SELL_LIST            2008
#define MAIN_HOUSE_RESIDENTS            2009
#define MAIN_HOUSE_RESIDENTS_LIST       2010
#define MAIN_HOUSE_RESIDENTS_INPUT      2011
#define MAIN_HOUSE_UPGRADE              2012
#define MAIN_HOUSE_UPGRADE_AGREE        2013
#define MAIN_HOUSE_SELF                 2014
#define MAIN_HOUSE_SELF_ADD             2015
#define MAIN_HOUSE_SELF_REMOVE          2016

#define HOUSE_PRICE_UP3                 (35000)     //70000
#define HOUSE_PRICE_UP6                 (75000)     //150000
#define HOUSE_PRICE_UP9                 (120000)    //240000
#define HOUSE_PRICE_UP12                (175000)    //350000
#define HOUSE_PRICE_UP15                (200000)    //400000
#define HOUSE_PRICE_UP18                (250000)    //500000
#define HOUSE_PRICE_UP21                (2500000)   //5000000

//----------------------------------------------------------------------------//

#define MAX_BUSINESS (108+1)

#define CREATE_COMPANY                  2050
#define MAIN_COMPANY                    2051
#define MAIN_COMPANY_ALTER_MSG          2052
#define MAIN_COMPANY_SAFE               2053
#define MAIN_COMPANY_RELEASE            2054
#define MAIN_COMPANY_SELL_LIST          2055
#define MAIN_COMPANY_SELL_INPUT         2056
#define MAIN_COMPANY_EMPLOYEE           2057
#define MAIN_COMPANY_EMPLOYEE_INPUT     2058

#define MAIN_UTILITIES                  2059
#define MAIN_FEED                       2060
#define MAIN_WEAPON                     2061

//----------------------------------------------------------------------------//

#define MAX_ACCESSORIES         10
#define MAX_STORE_ACCESSORIES   116
#define MAX_ACCESSORIES_CONNECT 5

//----------------------------------------------------------------------------//

#define SEX_GIRL            1
#define SEX_BOY             2

//----------------------------------------------------------------------------//

#define WORLD_DEFAULT   0
#define WORLD_ARENA     1000
#define WORLD_DS        1001

//----------------------------------------------------------------------------//

#define MAX_OBJECT_DS       24
#define MAX_PLACE_DS        10
#define MAX_TYPE_CNH        3
#define TYPE_CNH_ABC        0
#define TYPE_CNH_CHT        1
#define TYPE_CNH_ARRAIS     2

//----------------------------------------------------------------------------//

#define MIN_OFFER_WP        500
#define MAX_OFFER_WP        1000
#define MAX_ZONE_WP         12
#define MIN_WP              10
#define MAX_WP              50
#define WP_PRICE            55
#define WP_PRICE_AMMUNATION 500

//----------------------------------------------------------------------------//

#define EVENT_GIFT          0 // ON/OFF
#define EVENT_SWEET         0 // ON/OFF
