CMD:avls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,1022.4510,-1121.5958,23.8719);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Área Vip de Los Santos");
    return 1;
}
CMD:avlv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,2015.0763,1106.6337,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Área Vip de Las Venturas");
    return 1;
}
CMD:avsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,-2664.4136,-7.4449,6.1328);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Área Vip de San Fierro");
    return 1;
}
CMD:apls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,1962.2162,-2178.3967,13.5469);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Aeroporto de Los Santos");
    return 1;
}
CMD:aplv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid, 1712.0634, 1606.1857, 10.0156);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Aeroporto de Las Venturas");
    return 1;
}
CMD:apsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-1740.7712,-579.3079,16.3359);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Aeroporto de San Fierro");
    return 1;
}
CMD:apab(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,431.5682,2506.1760,16.4844);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Aeroporto Abandonado");
    return 1;
}
CMD:agls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,1154.0808,-1771.9812,16.5992);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Agencia de Los Santos");
    return 1;
}
CMD:aglv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,937.8450,1733.1957,8.8516);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Agencia de Las Venturas");
    return 1;
}
CMD:agsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,-2171.8110,252.0813,35.3378);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Agencia de San Fierro");
    return 1;
}
CMD:pfls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,1481.0637,-1770.9515,18.7958);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Prefeitura de Los Santos");
    return 1;
}
CMD:pflv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    SetPlayerPos(playerid,2447.0620,2376.2354,12.1635);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Prefeitura de Las Venturas");
    return 1;
}
CMD:pfsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-2765.8796,375.5812,6.3347);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Prefeitura de San Fierro");
    return 1;
}
CMD:dpls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1554.8657,-1675.6693,16.1953);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de Los Santos");
    return 1;
}
CMD:dplv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,2290.1218,2430.9775,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de Las Venturas");
    return 1;
}
CMD:dpsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-1605.5848,710.8436,13.8672);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de San Fierro");
    return 1;
}
CMD:dpdm(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,627.7621,-571.7207,17.5526);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de Dillimore");
    return 1;
}
CMD:dpfc(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid, -217.5554, 979.1621, 19.5025);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de Fort Carson");
    return 1;
}
CMD:dpap(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid, -2162.0627, -2385.7957, 30.6250);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de Angel Pine");
    return 1;
}
CMD:dpeq(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid, -1390.0345, 2638.0100, 55.9844);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Departamento de Polícia de El Quebrados");
    return 1;
}
CMD:hpls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1172.6787,-1323.3129,15.4022);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de Los Santos");
    return 1;
}
CMD:hplv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1607.3579,1815.6309,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de Las Venturas");
    return 1;
}
CMD:hpsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-2655.0662,639.1497,14.4531);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de San Fierro");
    return 1;
}
CMD:hpeq(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-1514.8217,2520.3232,55.9185);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de El Quebrados");
    return 1;
}
CMD:hpmg(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1241.8073,327.1022,19.7555);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de Montgomery");
    return 1;
}
CMD:hpfc(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-320.0716,1049.2637,20.3403);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Hospital de Fort Carson");
    return 1;
}
CMD:bcls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1778.3052,-1663.5337,14.4362);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Los Santos");
    return 1;
}
CMD:bclv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,2388.6733,2466.0430,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Las Venturas");
    return 1;
}
CMD:bcsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid, -1494.52, 920.06, 7.18);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de San Fierro");
    return 1;
}
CMD:bcfc(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-180.3883,1133.1510,19.7422);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Fort Carson");
    return 1;
}
CMD:bcmg(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1372.9271,405.2487,19.9555);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Montgomery");
    return 1;
}
CMD:bcpc(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,2302.9521,-16.2789,26.4844);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Palomino Creek");
    return 1;
}
CMD:bclb(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-828.0650,1503.6166,19.7585);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de Las Barrancas");
    return 1;
}
CMD:bceq(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-1480.8273,2592.3015,55.8359);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de El Quebrados");
    return 1;
}
CMD:bcbb(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,207.7767,-62.5814,1.6498);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Banco de BlueBerry");
    return 1;
}
CMD:ibls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1798.4763,-1578.3191,14.0849);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Imobiliaria de Los Santos");
    return 1;
}
CMD:iblv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,2413.2390,1123.8374,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Imobiliaria de Las Venturas");
    return 1;
}
CMD:ibsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-1881.1293,822.7573,35.1773);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Imobiliaria de San Fierro");
    return 1;
}
CMD:aels(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1519.0413,-1453.5895,14.2073);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Auto Escola de Los Santos");
    return 1;
}
CMD:aelv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,2183.2483,2295.2205,10.8203);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Auto Escola de Las Venturas");
    return 1;
}
CMD:aesf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-2026.5950,-101.3410,35.1641);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Auto Escola de San Fierro");
    return 1;
}
CMD:dtls(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1310.1411,-1367.8086,13.5408);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Detran de Los Santos");
    return 1;
}
CMD:dtlv(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,1173.1600,1349.0011,10.9219);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Detran de Las Venturas");
    return 1;
}
CMD:dtsf(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid,-2720.6375,127.7373,7.0391);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para o Detran de San Fierro");
    return 1;
}
CMD:bs(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

	SetPlayerPos(playerid, -2429.4663, 2329.1987, 4.9844);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Você se teletransportou para Bayside");
    return 1;
}
CMD:tps(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new textos[1000];
    strcat(textos, "{FF0000}•{FFFFFF} /avls - avlv - avsf : Áreas VIP's \n");
    strcat(textos, "{FF0000}•{FFFFFF} /apls - aplv - apsf - /apab : Aeroportos \n");
    strcat(textos, "{FF0000}•{FFFFFF} /agls - aglv - agsf : Agencia de Empregos \n");
    strcat(textos, "{FF0000}•{FFFFFF} /pfls - pflv - pfsf : Prefeitura \n");
    strcat(textos, "{FF0000}•{FFFFFF} /dpls - dplv - dpsf - dpdm : Departamento de Polícia \n");
    strcat(textos, "{FF0000}•{FFFFFF} /dpap - dpfc - dpeq : Departamento de Polícia \n");
    strcat(textos, "{FF0000}•{FFFFFF} /hpls - hplv - hpsf : Hospital \n");
    strcat(textos, "{FF0000}•{FFFFFF} /hpeq - hpmg - hpfc : Hospital \n");
    strcat(textos, "{FF0000}•{FFFFFF} /bcls - bclv - bcsf : Banco \n");
    strcat(textos, "{FF0000}•{FFFFFF} /bcfc - bcmg - bcpc : Banco \n");
    strcat(textos, "{FF0000}•{FFFFFF} /bclb - bceq - bcbb : Banco \n");
    strcat(textos, "{FF0000}•{FFFFFF} /ibls - iblv - ibsf : Imobilíaria \n");
    strcat(textos, "{FF0000}•{FFFFFF} /aels - aelv - aesf : Auto Escola \n");
    strcat(textos, "{FF0000}•{FFFFFF} /dtls - dtlv - dtsf : Detran \n");
    ShowPlayerDialog(playerid, 0, DIALOG_STYLE_MSGBOX, "{FF0000}Teletransportes", textos, "Fechar", "");
    return 1;
}
CMD:r(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id, txt[128];

    if(sscanf(params, "us[128]", id, txt))
        return SendClientMessage(playerid, Erro, "Digite: /R [id/nome] [resposta]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    format(String, MAX_STRING, "Resposta ~ Você respondeu a duvida ou o relatório do jogador(a) %s[%d]", PlayerInfo[id][Nome], id);
    SendClientMessage(playerid, White, String);
    format(String, MAX_STRING, "Resposta ~ %s %s respondeu : %s", CargoAdmin(playerid), PlayerInfo[playerid][Nome], txt);
    SendClientMessage(id, adm, String);
    return 1;
}
CMD:lc(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    for(new line = 0; line < 100; line++)
    {
        SendClientMessageToAll(White, " ");
    }
    return 1;
}

CMD:cornome(playerid)
{
    if(!IsPlayerHelper(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    ShowPlayerDialog(playerid, colorname, DIALOG_STYLE_INPUT, "{FF0000}Cor nome", "{FFFFFF}Digite um codigo em '{FF0000}HTML{FFFFFF}' abaixo\nPesquise no Google algo como {00FF00}Cores em HTML {FFFFFF}:\n{FF0000}Exemplo {FFFFFF}00FF00 = {00FF00}Calenzo", "Alterar", "Cancelar");
    return 1;
}

CMD:desprocurar(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /Desprocurar [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(PlayerInfo[id][Estrelas] == 0)
        return SendClientMessage(playerid, Erro, "O(A) Jogador(a) não está procurado(a)");

    PlayerInfo[id][Estrelas] = 0;
    format(String, 10, "%d", PlayerInfo[id][Estrelas]);
    PlayerTextDrawSetString(id, PlayerBarStatus[id][1], String);
    PlayerTextDrawShow(id, PlayerBarStatus[id][1]);

    format(String, MAX_STRING, "VRC-Admin ~ O(A) %s %s removeu todas as suas estrelas", CargoAdmin(id), PlayerInfo[playerid][Nome]);
    SendClientMessage(id, adm, String);
    format(String, MAX_STRING, "VRC-Admin ~ Você removeu todas as estrelas do jogador(a) %s[%d]", PlayerInfo[id][Nome], id);
    SendClientMessage(playerid, adm, String);
    return 1;
}
CMD:vercomandos(playerid)
{
    if(!IsPlayerHelper(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    if(viewcmds[playerid])
        viewcmds[playerid] = false;
    else
        viewcmds[playerid] = true;

    SendClientMessage(playerid, adm, "VRC-Admin ~ Comando efetuado com sucesso");
    return 1;
}
CMD:comandosadm(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new txt[3000];
    strcat(txt, "{FF0000}Comandos \t\t{1CEB00}Informações\n");

    switch(PlayerInfo[playerid][Admin])
    {
        case 1:
        {
            strcat(txt, "{87CEFF}/Ac \t\t{FFFFFF}Para digitar no chat da admininstração \n");
            strcat(txt, "{87CEFF}/Tps \t\t{FFFFFF}Para ver os teletransportes\n");
            strcat(txt, "{87CEFF}/Desprocurar \t\t{FFFFFF}Para desprocurar um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/Lc \t\t{FFFFFF}Para limpar o chat para todos jogador(a)\n");
            strcat(txt, "{87CEFF}/Ir \t\t{FFFFFF}Para ir até um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/Trazer \t\t{FFFFFF}Para puxar um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/Ejetar \t\t{FFFFFF}Para ejetar um(a) jogador(a) de um veículo\n");
            strcat(txt, "{87CEFF}/Injetar \t\t{FFFFFF}Para colocar um(a) jogador(a) em um veículo\n");
            strcat(txt, "{87CEFF}/Tapa \t\t{FFFFFF}Para dar um(a) tapa em um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/CriarVeiculo \t\t{FFFFFF}Para criar um veiculo em sua posição \n");
            strcat(txt, "{87CEFF}/EncherVida \t\t{FFFFFF}Para recuperar a vida de um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/EncherColete \t\t{FFFFFF}Para recuperar o colete de um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/R \t\t{FFFFFF}Para responder a dúvida de um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/RespawnVeiculos \t\t{FFFFFF}Para Respawnar todos os veiculos não em uso\n");
            strcat(txt, "{87CEFF}/Deslogar \t\t{FFFFFF}Para deslogar como membro da administração\n");
            strcat(txt, "{87CEFF}/Desbugar \t\t{FFFFFF}Para desbugar um(a) jogador(a) travado etc\n");
       }
        case 2:
        {
          	strcat(txt, "{87CEFF}/A \t\t{FFFFFF}Para mandar mensagem(ns) global\n");
            strcat(txt, "{87CEFF}/Ann \t\t{FFFFFF}Para mandar mensagem(ns) na tela\n");
            strcat(txt, "{87CEFF}/Cnn \t\t{FFFFFF}Para mandar mensagem(ns) na tela com o nome\n");
            strcat(txt, "{87CEFF}/CorNome \t\t{FFFFFF}Para alterar a cor do nome\n");
            strcat(txt, "{87CEFF}/Espiar \t\t{FFFFFF}Para espiar um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/PararEspiar \t\t{FFFFFF}Para parar de espiar o(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/Avisar \t\t{FFFFFF}Para avisar um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/GodModOn \t\t{FFFFFF}Para ficar com vida infinita\n");
            strcat(txt, "{87CEFF}/GodModOff \t\t{FFFFFF}Para remover a vida infinita\n");
            strcat(txt, "{87CEFF}/Kick \t\t{FFFFFF}Para kickar um(a) jogador(a) \n");
        	strcat(txt, "{87CEFF}/Punicao \t\t{FFFFFF}Para prender um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/Despunicao \t\t{FFFFFF}Para soltar um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/VerIP \t\t{FFFFFF}Para ver IP de um(a) jogador(a) \n");
            strcat(txt, "{87CEFF}/Congelar \t\t{FFFFFF}Para congelar/descongelar um(a) jogador(a) \n");
        }
        case 3:
        {
            strcat(txt, "{87CEFF}/Banir \t\t{FFFFFF}Para banir um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/DesBanir \t\t{FFFFFF}Para desbanir um(a) jogador(a)\n");
        }
        case 4:
        {
            strcat(txt, "{87CEFF}/DarArma \t\t{FFFFFF}Para dar uma arma para um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/IrCasa \t\t{FFFFFF}Para se teletransportar para a casa com esse id\n");
            strcat(txt, "{87CEFF}/PagarEvento \t\t{FFFFFF}Para pagar ao vencedor(a) do evento\n");
        }
        case 5:
        {
            strcat(txt, "{87CEFF}/Reiniciar \t\t{FFFFFF}Para reiniciar o servidor\n");
            strcat(txt, "{87CEFF}/AbrirServidor \t\t{FFFFFF}Para retirar a senha do servidor\n");
            strcat(txt, "{87CEFF}/FecharServidor \t\t{FFFFFF}Para fechar o servidor com senha\n");
        }
        case 6:
        {
            strcat(txt, "{87CEFF}/DarAdmin \t\t{FFFFFF}Para promover/rebaixar/remover jogador(a) da admininstração\n");
            strcat(txt, "{87CEFF}/DarLevel \t\t{FFFFFF}Para dar level(s) para um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/RemoverLevel \t\t{FFFFFF}Para remover level(s) de um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/DarReais \t\t{FFFFFF}Para dar real(is) de um(a) jogador(a)\n");
            strcat(txt, "{87CEFF}/RemoverReais \t\t{FFFFFF}Para remover real(is) de um(a) jogador(a)\n");
        }
    }

    format(String, MAX_STRING, "{C0C0C0}Comandos de {00CA00}%s", CargoAdmin(playerid));

    ShowPlayerDialog(playerid, 0, (IsPlayerMobile(playerid) ? DIALOG_STYLE_LIST : DIALOG_STYLE_TABLIST_HEADERS), String, txt, "Fechar", #);
    return 1;
}
CMD:deslogar(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    PlayerInfo[playerid][Admin] = 0;
    SetPlayerSkin(playerid, PlayerInfo[playerid][skin]);
    SendClientMessage(playerid, Yellow, "Agora você não está mais exercendo sua função");
    return 1;
}
CMD:respawnveiculos(playerid)
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    if(Respawnando)
        return SendClientMessage(playerid, Erro, "Veiculos não em uso já está sendo respawnados");

    Respawnando = true;
    TextDrawSetString(RespawnVeiculos, "~r~>> ~w~Respawn de veiculos nao em uso em ~g~30 ~w~segundos... ~r~<<");
    TextDrawShowForAll(RespawnVeiculos);
    SetTimer("Respawn1", 3*1000, false);
    return 1;
}
CMD:enchervida(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /EncherVida [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(playerid == id)
        return SendClientMessage(playerid, Erro, "Você não pode efetuar comando em sí mesmo");

    SetPlayerHealth(id, 100);
    format(String, MAX_STRING, "VRC-Admin ~ O(A) %s %s[%d] encheu sua vida", CargoAdmin(playerid), PlayerInfo[playerid][Nome], playerid);
    SendClientMessage(id, adm, String);
    format(String, MAX_STRING, "VRC-Admin ~ Você encheu a vida do(a) jogador(a) %s[%d]", PlayerInfo[id][Nome], id);
    SendClientMessage(playerid, adm, String);
    return 1;
}
CMD:enchercolete(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /EncherColete [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(playerid == id)
        return SendClientMessage(playerid, Erro, "Você não pode efetuar comando em sí mesmo");

    SetPlayerArmour(id, 100);
    format(String, MAX_STRING, "VRC-Admin ~ O(A) %s %s[%d] encheu seu colete", CargoAdmin(playerid), PlayerInfo[playerid][Nome], playerid);
    SendClientMessage(id, adm, String);
    format(String, MAX_STRING, "VRC-Admin ~ Você encheu o colete do(a) jogador(a) %s[%d]", PlayerInfo[id][Nome], id);
    SendClientMessage(playerid, adm, String);
    return 1;
}
CMD:injetar(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /Injetar [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(playerid == id)
        return SendClientMessage(playerid, Erro, "Você não pode efetuar comando em sí mesmo");

    new vehicleid = GetPlayerVehicleID(playerid);
    new seat = GetFreeSeat(vehicleid);

    PutPlayerInVehicle(id, vehicleid, seat);

    SendClientMessage(playerid, adm, "VRC-Admin ~ Comando efetuado com sucesso");
    format(String, MAX_STRING, "VRC-Admin ~ O(A) %s %s te colocou dentro de seu veiculo para o ajuda-lo!", CargoAdmin(playerid), PlayerInfo[playerid][Nome]);
    SendClientMessage(id, adm, String);
    return 1;
}
CMD:ejetar(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /Ejetar [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(playerid == id)
        return SendClientMessage(playerid, Erro, "Você não pode efetuar comando em sí mesmo");

    RemovePlayerFromVehicle(id);
    SendClientMessage(playerid, adm, "VRC-Admin ~ Comando efetuado com sucesso");
    format(String, MAX_STRING, "VRC-Admin ~ O(A) %s %s ejetou você do seu veiculo!", CargoAdmin(playerid), PlayerInfo[playerid][Nome]);
    SendClientMessage(id, adm, String);
    return 1;
}
CMD:desbugar(playerid, params[])
{
    if(!IsPlayerIntern(playerid))
        return SendClientMessage(playerid, Erro, "Comando Inválido");

    new id;

    if(sscanf(params, "u", id))
        return SendClientMessage(playerid, Erro, "Digite: /Desbugar [id/nome]");

    if(id == INVALID_PLAYER_ID || !PlayerInfo[id][Logado])
        return SendClientMessage(playerid, Erro, "Jogador(a) não conectado(a)");

    if(playerid == id)
        return SendClientMessage(playerid, Erro, "Você não pode efetuar comando em sí mesmo");

    if(IsArena[id])
        return SendClientMessage(playerid, Erro, "Jogador(a) está na Arena");

    if(PlayerInfo[id][frozen]) PlayerInfo[id][frozen] = false;

    TogglePlayerControllable(id, true);
    SetPlayerVirtualWorld(id, WORLD_DEFAULT);
    SetPlayerInterior(id, 0);
    ClearAnimations(id);

    format(String, MAX_STRING, "VRC-Admin ~ Jogador(a) %s[%d] desbugado(a)", PlayerInfo[id][Nome], id);
    SendClientMessage(playerid, adm, String);
    return 1;
}
