//Login 1 - 17
#define main_reais_vip          18
#define bank                    19
#define bank_balance            20
#define bank_draft              21
#define bank_deposit            22
#define bank_transfer           23
#define bank_transfer_value     24
#define main_cnh                25
#define main_fines              26
#define government              27
#define tuning                  28
#define paintjob                29
#define police                  30
#define neon                    31
#define arena                   32
#define arena_kits              33
#define rename                  34
#define colorname               35
#define wheel                   36
#define radio                   37
#define vip_color_tag           38
#define agency                  39
#define armedforces             40
#define hospital                41
#define hospital_sex            42
#define events                  43
#define vipss                   44
#define vip_area                45
#define mob                     46
#define honest                  47
#define transport               48
#define nitro                   49
#define hydraulic               50
#define main_reais              51
#define tanker_fuel             52
#define townhall                53
#define townhall_star           54
#define townhall_iptu_house     55
#define townhall_iptu_business  56
#define buy_cannabis            57
#define cost_accessories        58
#define cost_accessories1       59
#define school_bag              60
#define school_bag_weapon       61
#define school_bag_get          62
#define school_bag_acce         63
#define school_bag_acce_edit    64
#define school_bag_acce_sell    65
#define anticheat               66
#define realestate              67
#define base_menu               68
#define base_name               69
#define base_vehicle            70
#define base_vehicle_state      71
#define base_weapon             72
#define base_members            73
#define base_members_alter      74
#define base_members_add        75
#define base_members_add_sub    76
#define base_dm                 77
#define base_tag                78
#define base_lock               79
#define base_locked             80
#define base_pass               81
#define study                   82
#define help                    83

//Banimento     96 - 99
//Imobilária    100 - 200
//Houses        5000 - 5015
//Companys      5016 - 5050
//Vehicles      5051 - 5059
//GPS           5060 - 5073
//#define MAIN_FUEL 5100

#define MAX_GAS_MAP         32
#define MAX_GAS_VEHICLE     6

//ATTACH
#define MAX_ACCESSORIES     5 //0-4 acessories
#define ATTACH_INDEX_THIEF  5
#define GS_PISTOL           6
#define GS_SHOTGUN          7
#define GS_SUBMACHINEGUN    8
#define GS_MACHINEGUN       9

//BASES
#define MAX_BASES               (3)
#define MAX_BASE_SUB            (1)
#define MAX_BASE_MEMBERS        (20)
#define MAX_BASE_NAME           (30)
#define MAX_BASE_TAG_NAME       (10)
#define MAX_VEHICLE_BASE        (4)
#define MAX_BASE_PASS           (10)
#define BASE_VEHICLE_MODEL      (560)
#define BASE_MONEY              (250000)
#define BASE_REAIS              (25)
#define BASE_PICKUP_SELL        (1313)
#define BASE_PICKUP_BUY         (1313)
#define BASE_MAP_SELL           (62)
#define BASE_MAP_BUY            (59)

//Virtual Worlds
#define WORLD_DEFAULT   0
#define WORLD_ARENA     1000
#define WORLD_DS        1001

//CNH
#define MAX_OBJECT_DS       24
#define MAX_PLACE_DS        10
#define MAX_TYPE_CNH        3
#define TYPE_CNH_ABC        0
#define TYPE_CNH_CHT        1
#define TYPE_CNH_ARRAIS     2
