/*
#include YSI\y_hooks

hook OnPlayerText(playerid, text[])
{
 if(text[0] == '!' && strlen(text) > 1)
    {
        format(String, sizeof(String), "** {FFFFFF}Chat-Base {FFFFFF}(( %s[%d]: %s ))", PlayerInfo[playerid][Nome], playerid, text);
        ProxDetector(30.0, playerid, String, GetPlayerColor(playerid), GetPlayerColor(playerid), GetPlayerColor(playerid), GetPlayerColor(playerid), GetPlayerColor(playerid));
        return 0;
	}
    return 1;
}
*/
